version: "3"
services:
  api1:
    build: ./api
    networks:
      - default
  api2:
    build: ./api
    networks:
      - default
  webserver:
    build: ./webserver
    volumes:
      - ./webserver/src:/var/www/html
    environment:
      API: http://10.10.17.150:83/api
    networks:
      - default

  proxy:
    image: nginx
    ports:
      - "83:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    networks:
      - default
    depends_on:
      - api1
      - api2
      - webserver
